# Generated by Django 3.2.9 on 2021-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
